# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  glad_config = debug
  imgui_config = debug
  assimp_config = debug
  Editor_config = debug
  ToyEngine_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  glad_config = release
  imgui_config = release
  assimp_config = release
  Editor_config = release
  ToyEngine_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  glad_config = dist
  imgui_config = dist
  assimp_config = dist
  Editor_config = dist
  ToyEngine_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW glad imgui assimp Editor ToyEngine

.PHONY: all clean help $(PROJECTS) Applications Dependencies

all: $(PROJECTS)

Applications: Editor

Dependencies: GLFW assimp glad imgui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C ToyEngine/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C ToyEngine/vendor/glad -f Makefile config=$(glad_config)
endif

imgui: GLFW
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C ToyEngine/vendor/dearimgui -f Makefile config=$(imgui_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C ToyEngine/vendor/assimp -f Makefile config=$(assimp_config)
endif

Editor: ToyEngine
ifneq (,$(Editor_config))
	@echo "==== Building Editor ($(Editor_config)) ===="
	@${MAKE} --no-print-directory -C Editor -f Makefile config=$(Editor_config)
endif

ToyEngine: GLFW glad imgui assimp
ifneq (,$(ToyEngine_config))
	@echo "==== Building ToyEngine ($(ToyEngine_config)) ===="
	@${MAKE} --no-print-directory -C ToyEngine -f Makefile config=$(ToyEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C ToyEngine/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C ToyEngine/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C ToyEngine/vendor/dearimgui -f Makefile clean
	@${MAKE} --no-print-directory -C ToyEngine/vendor/assimp -f Makefile clean
	@${MAKE} --no-print-directory -C Editor -f Makefile clean
	@${MAKE} --no-print-directory -C ToyEngine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   imgui"
	@echo "   assimp"
	@echo "   Editor"
	@echo "   ToyEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"